### ISSUE TITLE
Add team search button

### ISSUE THREAD

**Issue by timonla** [flashkillapp/flashkill#15]
The team search of flashkill is no longer needed, since the new page now has its own [team search](https://liga.99damage.de/de/leagues/teams).
However, there seems to be no easy way to navigate to this url. Come up with a good place to insert a button to open the team search and insert it, redirecting to `https://liga.99damage.de/de/leagues/teams`.

**Comment by Serhazor** [comment]
Is it only in german or is there an english version available?

**Comment by Lyannic** [comment]
@Serhazor Since 99damage is only available in German, the team search is also only available in German 😞
